# Generated by Django 5.0 on 2024-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_app_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_grant_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('p_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
